language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  allow_failures:
    - php: hhvm

env:
  global:
    - YII_ENV=test
    - APP_PRETTY_URLS=0
    - DB_PORT_3306_TCP_ADDR=localhost
    - DB_ENV_MYSQL_DATABASE=p4_test
    - DB_ENV_MYSQL_USER=test
    - DB_ENV_MYSQL_PASSWORD=test123
install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer self-update && composer --version
  - composer global require "fxp/composer-asset-plugin:1.0.0-beta4"
  - cp .env-dist .env
  - composer install --dev --prefer-dist

before_script:
  - sed -i.bak 's/localhost:80/localhost:8080/' tests/codeception/acceptance.suite.yml
  - php -S localhost:8080 -t web > /dev/null 2>&1 &
  - mysql -e 'create database p4_test;'
  - mysql -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test123';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON * . * TO 'test'@'localhost';"
  - php yii app/setup --interactive=0
  - php yii app/setup-tests --interactive=0

script:
  - codecept -v run

after_success:
  - php yii app/setup-docs --interactive=0
  - php yii app/generate-docs --interactive=0