version: '3'
services:

  php:
    image: cornernote/php
    ports:
      - 80:80
    volumes:
      #- ./build/php/config/root/.bashrc:/root/.bashrc
      #- ./build/php/config/root/.composer/auth.json:/root/.composer/auth.json
      #- ./build/php/config/usr/local/etc/php/conf.d/base.ini:/usr/local/etc/php/conf.d/base.ini
      #- ./build/php/config/usr/local/etc/php-fpm.d/zzz-app.conf:/usr/local/etc/php-fpm.d/zzz-app.conf
      #- ./.git:/app/.git
      - ./.env:/app/.env
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./codeception.yml:/app/codeception.yml
      - ./yii:/app/yii
      - ./data:/app/data
      - ./docs:/app/docs
      - ./runtime:/app/runtime
      - ./src:/app/src
      - ./tests:/app/tests
      - ./web:/app/web
      - ./vendor:/app/vendor

  db:
    image: percona:8.0
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --sql-mode="ERROR_FOR_DIVISION_BY_ZERO,IGNORE_SPACE,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,PIPES_AS_CONCAT,REAL_AS_FLOAT"
    environment:
      - MYSQL_USER=test
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis:5.0-alpine
