version: '3'
services:

  php:
    image: cornernote/php
    ports:
      - 80:80
    volumes:
      - ./.git:/app/.git
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./codeception.yml:/app/codeception.yml
      - ./yii:/app/yii
      - ./yiish:/app/yiish
      - ./data:/app/data
      - ./docs:/app/docs
      - ./runtime:/app/runtime
      - ./src:/app/src
      - ./tests:/app/tests
      - ./web:/app/web
      - ./vendor:/app/vendor

  db:
    image: percona:8.0
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password --sql-mode="ERROR_FOR_DIVISION_BY_ZERO,IGNORE_SPACE,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,PIPES_AS_CONCAT,REAL_AS_FLOAT"
    environment:
      - MYSQL_USER=app
      - MYSQL_DATABASE=app
      - MYSQL_PASSWORD=app
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis:5.0-alpine
